### ISSUE TITLE
hola, can we make a connection.

### ISSUE THREAD

**Issue by Rodert** [ilkamo/jupiter-go#12]
I have also recently been using blockchain technologies such as solana in the hope of establishing closer communication.

**Comment by ilkamo** [comment]
Sure thing man! You can DM on **https://twitter.com/il_kamo** or discord -> **ilkamo** :) @Rodert

**Comment by Rodert** [comment]
> Sure thing man! You can DM on **https://twitter.com/il_kamo** or discord -> **ilkamo** :) @Rodert

good, i follow twitter. i am `jack wang`. but is not new massage.
