### ISSUE TITLE
Update dependencies for examples to fix nil pointer dereference

### ISSUE THREAD

**Issue by prdsrm** [ilkamo/jupiter-go#24]
### Reproduce the error

Run the example: `./examples/swap` a few times. You will encounter the following nil pointer dereference, occurring at line 132 in the `solana/client.go` file:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x1008dcd0c]

goroutine 1 [running]:
github.com/ilkamo/jupiter-go/solana.Client.CheckSignature({0x100a5d778?, {0x100a617d8?, 0x140001120a0?}, {0x14000116090?}}, {0x100a61dd0, 0x100d2b060}, {0x1400009e780?, 0x4f0?})
        go/pkg/mod/github.com/ilkamo/jupiter-go@v0.0.4/solana/client.go:132 +0x18c
main.main()
        jupiter-go/_examples/swap/main.go:89 +0x3b4
```

### Simple fix

This was already fix in a newer version I supposed, but the dependencies haven't been updated.

Update the dependencies in the file:
`go get -u github.com/ilkamo/jupiter-go`
`go mod tidy`

I know it sounds like a dumb issue, but I've been wondering why it didn't work for a while, without thinking that it was just a version error...

**Comment by ilkamo** [comment]
@prdsrm thanks for reporting this, I pushed a new version with updated dependencies.
