### ISSUE TITLE
Use `int64` instead of `int` for amounts

### ISSUE THREAD

**Issue by shackra** [ilkamo/jupiter-go#27]
I use shopspring/decimal for managing amounts, when I want to pass the integer to jup.ag I do the following:

```
	quoteResponse, err := w.jup.GetQuote(context.TODO(), &jupiter.GetQuoteParams{
		InputMint:   m,
		OutputMint:  SOLMint,
		Amount:      int(amount.CoefficientInt64()),
		SlippageBps: &slippageBsp,
	})
```

I need to do an ugly casting to `int` from `int64`

**Comment by ilkamo** [comment]
@shackra part of the code is generated from the openapi definition however I have an idea how to improve it. I will look into it in a few days.

**Comment by ilkamo** [comment]
@shackra I pushed a new version, please check it works as expected.

**Comment by shackra** [comment]
yes, that commit should do it, thanks!
