### ISSUE TITLE
several problems

### ISSUE THREAD

**Issue by Rodert** [ilkamo/jupiter-go#5]
halo, this good.

How can I get this up and running.

**Comment by ilkamo** [comment]
Hi @Rodert, give me a few days and I will add an example folder explaining step-by-step all you need to get this up and running.

**Comment by ilkamo** [comment]
@Rodert I have added an example in the following folder: https://github.com/ilkamo/jupiter-go/blob/main/_examples/swap/main.go

Just `cd` into `jupiter-go/_examples/swap`, replace the string `"your public key here"` in the code with your public wallet address and then run `go mod tidy` and `go run main.go`. You should receive back from Jupiter an example of swap instruction.

**Comment by Rodert** [comment]
> @Rodert I have added an example in the following folder: https://github.com/ilkamo/jupiter-go/blob/main/_examples/swap/main.go
> 
> Just `cd` into `jupiter-go/_examples/swap`, replace the string `"your public key here"` in the code with your public wallet address and then run `go mod tidy` and `go run main.go`. You should receive back from Jupiter an example of swap instruction.

thanks.

**Comment by Rodert** [comment]
> @Rodert I have added an example in the following folder: https://github.com/ilkamo/jupiter-go/blob/main/_examples/swap/main.go
> 
> Just `cd` into `jupiter-go/_examples/swap`, replace the string `"your public key here"` in the code with your public wallet address and then run `go mod tidy` and `go run main.go`. You should receive back from Jupiter an example of swap instruction.

@ilkamo If I want to send a transaction package signature to the chain, how do I do it? Can I understand "swap" as the obtained data to be released?

**Comment by Rodert** [comment]
> > @Rodert I have added an example in the following folder: https://github.com/ilkamo/jupiter-go/blob/main/_examples/swap/main.go
> > Just `cd` into `jupiter-go/_examples/swap`, replace the string `"your public key here"` in the code with your public wallet address and then run `go mod tidy` and `go run main.go`. You should receive back from Jupiter an example of swap instruction.
> 
> @ilkamo If I want to send a transaction package signature to the chain, how do I do it? Can I understand "swap" as the obtained data to be released?

this is done.
