### ISSUE TITLE
Is there an error in your example code that doesn't run?

### ISSUE THREAD

**Issue by mingtianquan** [ilkamo/jupiter-go#6]

**Comment by ilkamo** [comment]
@mingtianquan I have extended the _README.md_ and I have added an example in the following folder: https://github.com/ilkamo/jupiter-go/blob/main/_examples/swap/main.go

Just cd into `jupiter-go/_examples/swap`, replace the string `"your public key here"` in the code with your public wallet address and then run `go mod tidy` and `go run main.go`. You should receive back from Jupiter an example of swap instruction.

**Comment by mingtianquan** [comment]
Unable to run. invalid PostSwapWithResponse response reported this error
