### ISSUE TITLE
How can tokens be exchanged back into sol

### ISSUE THREAD

**Issue by mingtianquan** [ilkamo/jupiter-go#8]

**Comment by mingtianquan** [comment]
quoteResponse, err := jupClient.GetQuoteWithResponse(ctx, &jupiter.GetQuoteParams{
		InputMint:   "So11111111111111111111111111111111111111112",
		OutputMint:  "WENWENvqqNya429ubCdR81ZmD69brwQaaBYY6p3LCpk",
		Amount:      100000,
		SlippageBps: &slippageBps,
	})

These two tokens cannot be exchanged by swapping their positions. For example, I need Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McE8BenwNYB (USDT) to exchange back for sol
Or Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McE8BenwNYB exchange
EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v (USDC)
Trying to change the address here doesn't work

**Comment by ilkamo** [comment]
@mingtianquan, let's say you want to get the following quote: **1 USDT** for **SOL**. This is the example request:

```
quoteResponse, err := jupClient.GetQuoteWithResponse(ctx, &jupiter.GetQuoteParams{
	InputMint:   "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
	OutputMint:  "So11111111111111111111111111111111111111112",
	Amount:      1000000, // 1 USDT
	SlippageBps: &slippageBps,
})
```

The same is valid for 1 USDT to USDC. Just change the **OutputMint** address.

```
quoteResponse, err := jupClient.GetQuoteWithResponse(ctx, &jupiter.GetQuoteParams{
	InputMint:   "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
	OutputMint:  "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
	Amount:      1000000, // 1 USDT
	SlippageBps: &slippageBps,
})
```

I hope this can help you. Btw, if you find it helpful, please consider leaving a star on the repository.
